logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'} %5p [%t] %c{1}.%M:%L - %m%n"

management:
  observations:
    key-values:
      application: ObservabilityDemo

  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus

  metrics:
    enable:
      demo.compute.latency: true
      demo.hello.latency: true
